name: Sync PM2.5 Data

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour on the hour
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests pandas pytz

      - name: Run Sync Script
        run: python fetch_pm25.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sg_haze.db
          git commit -m "Automated Haze Sync: $(date -u)" || exit 0
          git push
